server:
  port: 8085

spring:
  application:
    name: api-gateway

  app:
    config:
      keycloak:
        internal-url: ${APP_CONFIG_KEYCLOAK_INTERNAL_URL}
        external-url: ${APP_CONFIG_KEYCLOAK_EXTERNAL_URL}
        realm: ${APP_CONFIG_KEYCLOAK_REALM}

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false

      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**

        - id: fund-transfer-service
          uri: lb://fund-transfer-service
          predicates:
            - Path=/api/fund-transfers/**

        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/api/accounts/**

        - id: sequence-generator
          uri: lb://sequence-generator
          predicates:
            - Path=/api/sequence/**

        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/api/transactions/**

  security:
    oauth2:
      client:
        provider:
          keycloak:
            authorization-uri: ${app.config.keycloak.external-url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/auth
            user-info-uri: ${app.config.keycloak.external-url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/userinfo
            token-uri: ${app.config.keycloak.internal-url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/token
            jwk-set-uri: ${app.config.keycloak.internal-url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/certs

        registration:
          banking-service-client:
            provider: keycloak
            client-id: banking-service-client
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: ${APP_REDIRECT_URI}
            scope: openid

      resourceserver:
        jwt:
          issuer-uri: ${app.config.keycloak.internal-url}/realms/${app.config.keycloak.realm}

# ✅ ONLY ONE eureka (and OUTSIDE spring)
eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/